defaultPlacement: end
enableVersioning: true
handle: color
name: Color
propagationMethod: all
siteSettings:
  61da9f82-35d6-45cd-be8e-e2e50071b05d: # Floresco
    enabledByDefault: true
    hasUrls: true
    template: color/_entry
    uriFormat: 'color/{slug}'
type: channel
