columnSuffix: null
contentColumnType: string
fieldGroup: 133c78df-33fb-423b-b305-8817da04930d # Common
handle: referenceColor
instructions: null
name: 'Reference Color'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:fb5b2491-c473-4e5d-8952-94ed4820770c' # Color
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
