fieldLayouts:
  8e54a1c1-5bce-48ba-b080-76106f55475b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b3bffc6f-0e78-4516-9465-ec02aa04d554
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 107ada6b-b0d4-44dd-85c1-b0f00b339dd2 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd1e7791-700d-40ea-b9ed-f71d7608912b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 204cae97-3fe9-4f7a-943a-a5f4cb518611
        userCondition: null
handle: branding
hasTitleField: false
name: Branding
section: f5648cce-da6c-4419-8deb-6169e914aafc # Branding
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
